### ISSUE TITLE
 not working

### ISSUE THREAD

**Issue by merci20** [Alygnt/Clifty#25]
localhost does not work. it does not connect to any browser. Ngrok is the same; it is written that the host has been banned.
the other solutions do not work either. Need an update

**Comment by Alygnt** [comment]
Hi @merci20 , 
I am extremely sorry for the errors you faced.... I just wanna say that the tool works perfectly fine... And the tunnels except localxpose all are working.
Here is the reason why your facing such issue:
1.Localhost - this could be because of your internet speed or some permissions error
2.Ngrok - The ngrok has recognised that your using it's service for phishing and banned you. The only solution is to create a new account (I will recommend to create will temp mail like temp-mail.org) and configure your terminal with it
3.Cloudflare - it needs very fast internet service like ethernet or broadband
4. Localxpose - The localxpose server is currently down so it won't work 

Just check all the these methods and contact me in issues or discussions tab

And also I am soon giving a huge update to the tool. It has all the marvelous features and I am sure that you will love it.

Thanks and regards,
Alygnt

**Comment by merci20** [comment]
nothing is working
cloudflare running with another but not with your system
your ngrok server is really bad
you system need an update
